### 14. Lambda Functions in Python

###### What is Lambda function?

A lambda function is a small, anonymous(nameless) cunction written in one single line.


📌 Simple Define
> _A lambda funciton is a one-line function without a name_

#### Why Lambda Functions are Used?

* ꪜShort and clean code
* ꪜused for temporary operation
* ꪜCommon with map(), filter(), readuce(),apply()
* ꪜImprove readablity in simple logic.

##### Normal Function VS Lambda function 

###### Syntax
`(lambda variable:expression)(argument)`


### Normal Function

In [2]:
def square(x):
    return x*x
square(2)

4

### Lambda Function

In [3]:
(lambda x:x*x)(2)

4

### Syntax of Lambda function

`lambda arguments:exrpression`

📌 Rules:
* ꪜCan have multiple arguments
* ꪜOnly one expression
* ꪜAutomatically returns result
* ꪜNo return keyword

### Basic Examples

### 1. add two numbers

In [6]:
add = (lambda a,b:a+b)

In [5]:
print(add(10,20))

30

In [7]:
print(add(50,10))

60

### 2. square of a number

In [9]:
square = (lambda x:x**2)  #2²
square(5)

25

In [10]:
square(10)

100

In [11]:
square(25)

625

### 3. Check Even of Odd

In [24]:
even = (lambda x:"Even" if x%2==0 else "Odd")

print(even(2))

Even

In [23]:
print(even(7))

Odd

#### Lambda with Multiple arguments

In [28]:
max_num = (lambda a,b,c:a if a>b and a>c else(b if b>c else c))

In [ ]:
a = 10
b = 9
c = 11

In [29]:
max_num(10,11,12)

12

#### Lambda Built-in Functions
1. filter()
2. map()
3. reduce()
4. sorting()
5. apply()

### Lambda with filter()
Filter elemnets based on condition

In [30]:
numbers = [1,2,3,4,5,6,7,8,9,10]

### Normal Function

In [32]:
def evenNum(x):
    return x%2==0
evenNum(3)

False

In [34]:
numbers = [1,2,3,4,5,6,7,8,9,10]
list(filter(evenNum,numbers))

[2, 4, 6, 8, 10]

Styntax:

`filter(function, sequence)`

### Lambda Function

In [36]:
numbers = [1,2,3,4,5,6,7,8,9,10]
list(filter(lambda a:a%2==0, numbers))

[2, 4, 6, 8, 10]

### Lambda with map() 

Purpose: Apply a funciton to each element in a list

### Normal Function

In [39]:
numbers = [1,2,3,4,5,6,7,8,9,10]


def sqrNum(a):
    return a**2
sqrNum(2)

4

In [41]:
numbers = [1,2,3,4,5,6,7,8,9,10]
list(map(sqrNum,numbers))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Lambda function

In [42]:
numbers = [1,2,3,4,5,6,7,8,9,10]

tuple(map(lambda a:a**2,numbers))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

### Lambda with reduce()

📌 Required Library `functools`

In [44]:
from functools import reduce

### Normal function

In [53]:
numbers = [1,2,3,4,5,6,7,8,9,10]
# sum(numbers)

def sumValue(a,b):
    return a+b

In [54]:
reduce(sumValue,numbers)

55

### lambda function

In [56]:
numbers = [1,2,3,4,5,6,7,8,9,10]
reduce(lambda x,y:x+y,numbers )

55

### 5. Lambda with sorting

In [1]:
students = [("Ram",89),("Anita",66),("Kiran",10)]

sorted_students = sorted(students,key = lambda x:x[1])
print(sorted_students)

[('Kiran', 10), ('Anita', 66), ('Ram', 89)]

In [2]:
students = [("Ram",89),("Anita",66),("Kiran",10)]

sorted_students = sorted(students,key = lambda x:x[0])
print(sorted_students)

[('Anita', 66), ('Kiran', 10), ('Ram', 89)]

### 🔷 When Not Use Lambda 

* ❌ Complex Logic
* ❌ Multiple Conditions
* ❌ Multiple lines
* ❌ Resusable business Logic

📌 Used def instead


------
### One-Liner about lambda
* ꪜLambda is an anonymous function
* ꪜWritten in one line
* ꪜNo return keyword
* ꪜUsed with map(), reduce(), filter(), sorted(), apply()
* ꪜImport code readability for small tasks

### 🔷 Summary 
> Lambda function are small, one-line, nameless funciton used for short operations.

### 🔷 Lambda with apply() in python (Pandas) 

### What is apply() ?

apply() is used in Pandas to apply a function(including lambda) to:

* Each column
* Each row
* Each cell(Series)

📌 Simple Define
> apply() applies a function to data elements.

----
### 🔷 Why Use Lambda with apply()?

* ✓short, clean logic
* ✓No need to define full function.
* ✓Best for data transformation
* ✓Widely used in Data Science
-----

🔷 Required Library 

`import pandas as pd`

### 🔷 Lambda with apply() on a Series

In [3]:
import pandas as pd

In [10]:
data = [1,2,3,4,5,6,7,8,9,10]
print(data,type(data))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>

In [11]:
dataSeries = pd.Series(data)
print(dataSeries)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [12]:
data = [1,2,3,4,5,6,7,8,9,10]
print(data,type(data))

for i in data:
    print(i**2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>
1
4
9
16
25
36
49
64
81
100

In [13]:
dataSeries = pd.Series(data)
print(dataSeries)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [15]:
# for i in dataSeries:
#     print(i)

In [16]:
result = dataSeries.apply(lambda x:x**2)
print(result)

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int64

Notes:

* Lambda applied to each value
* Similar to map()

## 2. Lambda with apply() on DataFrame Column

Example: Increase salary by 10%

In [31]:
data = {
    "Name":["Ram","Anita","Kiran"],
    "Salary":[40000,50000,45000]
}


df = pd.DataFrame(data)
df

    Name  Salary
0    Ram   40000
1  Anita   50000
2  Kiran   45000

In [32]:
df["10% Increment"] = df["Salary"].apply(lambda x:((x*1/10)))
df

    Name  Salary  10% Increment
0    Ram   40000         4000.0
1  Anita   50000         5000.0
2  Kiran   45000         4500.0

In [33]:
# Method 1: Total Salary

df["Total Salary"] = df['Salary'] + df["10% Increment"]
df

    Name  Salary  10% Increment  Total Salary
0    Ram   40000         4000.0       44000.0
1  Anita   50000         5000.0       55000.0
2  Kiran   45000         4500.0       49500.0

In [34]:
df["Total Salary Increment"] = df["Salary"].apply(lambda x:x+((x*1/10)))
df

    Name  Salary  10% Increment  Total Salary  Total Salary Increment
0    Ram   40000         4000.0       44000.0                 44000.0
1  Anita   50000         5000.0       55000.0                 55000.0
2  Kiran   45000         4500.0       49500.0                 49500.0